 name: Backup to S3
 on:
  schedule:
    - cron: '0 0 * * *' # Adjust the cron schedule to your liking
  push:
    branches:
      - main

 jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Backup repository
      run: |
        # Create a ZIP archive of the repository
        zip -r backup.zip .
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
          aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

    - name: Upload to S3
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      

        # Upload the ZIP file to the S3 bucket
      run:  aws s3 sync backup.zip s3://mysonpriyansh
      
    
    - name: Cleanup
      run: |
        # Remove the ZIP file
        rm backup.zip

